"""empty message

Revision ID: 66f18cfcf091
Revises: d90ffbe1f80e
Create Date: 2022-05-23 16:39:45.608728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f18cfcf091'
down_revision = 'd90ffbe1f80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('endereco_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cliente', 'endereco', ['endereco_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'endereco_id')
    # ### end Alembic commands ###
