"""empty message

Revision ID: b203895db024
Revises: 00fc8a42aba4
Create Date: 2022-05-27 11:42:44.510469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b203895db024'
down_revision = '00fc8a42aba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cliente_ibfk_1', 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'endereco_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('endereco_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cliente_ibfk_1', 'cliente', 'endereco', ['endereco_id'], ['id'])
    # ### end Alembic commands ###
