"""empty message

Revision ID: d90ffbe1f80e
Revises: 20bc7c6de53c
Create Date: 2022-05-23 16:16:28.734920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90ffbe1f80e'
down_revision = '20bc7c6de53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('bairro', sa.String(length=50), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco')
    # ### end Alembic commands ###
